config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/index' => 'home#index'
  
  get '/donate' => 'home#donate'
  get '/about' => 'home#about'
  get '/achievement' => 'home#achievement'
  get '/vicinity' => 'home#vicinity'
  get '/mission' => 'home#mission'
  get '/site_map' => 'home#site_map'
  get '/contact' => 'home#contact'
  get '/event' => 'home#event'
  get '/media' => 'home#media'
  get '/faq' => 'home#faq'
  get '/open_space' => 'home#open_space'
  get '/mangroves' => 'home#mangroves'
  get '/playground' => 'home#playground'
  get '/encroachment' => 'home#encroachment'
  get '/protect_green_zone' => 'home#protect_green_zone'
  get '/safe_neighbourhood' => 'home#safe_neighbourhood'
  get '/help_line' => 'home#help_line'
  get '/hospital' => 'home#hospital'
  get '/college' => 'home#college'
  get '/school' => 'home#school'
  get '/fire_brigade' => 'home#fire_brigade'
  get '/ambulance' => 'home#ambulance'
  get '/bmc' => 'home#bmc'

  get '/base/:action' => 'base'

  get '/forums/recent' => 'sb_posts#index', :as => :recent_forum_posts
  get '/photos/recent' => 'photos#recent', :as => :recent_photos

  resources :authorizations
  match '/auth/:provider/callback' => 'authorizations#create', :as => :callback
  get '/auth/failure' => 'authorizations#failure'

  resources :sb_posts, :as => 'all_sb_posts' do
    collection do
      get :search
      get :monitored
    end
  end

  resources :monitorship
  resources :sb_posts do
    collection do
      get :search
      get :monitored
    end
  end

  resources :forums do
    resources :sb_posts
    
    resources :moderators
    resources :topics do
      resources :sb_posts
      resource :monitorship
    end
  end

  get '/forums' => 'forums#index', :as => :forum_home

  get 'sitemap.xml' => 'sitemap#index', :format => 'xml'
  get 'sitemap' => 'sitemap#index'

  get '/' => 'base#site_index', :as => :home

  scope "/admin" do
    get 'dashboard' => 'homepage_features#index', :as => :admin_dashboard
    get 'users' => 'admin#users', :as => :admin_users
    get 'messages' => 'admin#messages', :as => :admin_messages
    get 'comments' => 'admin#comments', :as => :admin_comments
    get 'tags' => 'tags#manage', :as => :admin_tags
    get 'events' => 'admin#events', :as => :admin_events
    get 'clear_cache' => 'admin#clear_cache', :as => :admin_clear_cache
    get 'subscribers(.:format)' => "admin#subscribers", :as => :admin_subscribers
    get 'activate_user' => "admin#activate_user", :as => :admin_activate_user
    get 'deactivate_user' => 'admin#deactivate_user', :as => :admin_deactivate_user
    
    resources :pages, :as => :admin_pages do
      member do
        get :preview
      end
    end
  end
  
  get 'pages/:id' => 'pages#show', :as => :pages
  
  
  get '/login' => 'sessions#new', :as => :login
  get '/signup' => 'users#new', :as => :signup
  get '/logout' => 'sessions#destroy', :as => :logout
  
  get '/signup/:inviter_id/:inviter_code' => 'users#new', :as => :signup_by_id
  get '/forgot_password' => 'password_resets#new', :as => :forgot_password
  resources :password_resets
  get '/forgot_username' => 'users#forgot_username', :as => :forgot_username
  post '/forgot_username' => 'users#forgot_username'
  post '/resend_activation' => 'users#resend_activation', :as => :resend_activation
  
  get '/new_clipping' => 'clippings#new_clipping'
  post '/load_images_from_uri' => 'clippings#load_images_from_uri', :format => 'js'  
  get '/clippings(/page/:page)' => 'clippings#site_index', :as => :site_clippings
  get '/clippings.rss' => 'clippings#site_index', :as => :rss_site_clippings, :format => 'rss'
  
  get '/featured(/page/:page)' => 'posts#featured', :as => :featured
  get '/featured.rss' => 'posts#featured', :as => :featured_rss, :format => 'rss'
  get '/popular(/page/:page)' => 'posts#popular', :as => :popular
  get '/popular.rss' => 'posts#popular', :as => :popular_rss, :format => 'rss'
  get '/recent(/page/:page)' => 'posts#recent', :as => :recent
  get '/recent.rss' => 'posts#recent', :as => :recent_rss, :format => 'rss'
  get '/rss' => 'base#rss_site_index', :as => :rss_redirect
  get '/site_index.rss' => 'base#site_index', :as => :rss, :format => 'rss'
  get '/advertise' => 'base#advertise', :as => :advertise
  get '/css_help' => 'base#css_help', :as => :css_help
  get '/about' => 'base#about', :as => :about
  get '/faq' => 'base#faq', :as => :faq
  get '/footer_content' => 'base#footer_content', :as => :footer_content

  get '/account/edit' => 'users#edit_account', :as => :edit_account_from_email

  get '/friendships.xml' => 'friendships#index', :as => :friendships_xml, :format => 'xml'
  get '/friendships' => 'friendships#index', :as => :friendships

  get 'manage_photos' => 'photos#manage_photos', :as => :manage_photos
  post 'create_photo.js' => 'photos#create', :as => :create_photo, :format => 'js'

  resources :sessions
  resources :statistics do
    collection do
      get :activities
      get :activities_chart
    end
  end

  resources :tags do
    get :auto_complete_for_tag_name, :on => :collection
  end
  get '/tags/:id/:type' => 'tags#show', :as => :show_tag_type
  get '/search/tags' => 'tags#show', :as => :search_tags
  
  resources :categories
  post '/categories/show_tips' => 'categories#show_tips', :as => :categories_show_tips

  resources :events do
    get 'page/:page', :action => :index, :on => :collection
    collection do
      get :past
      get :ical
    end
    member do
      get :clone
    end
    resources :rsvps
  end

  scope '/:favoritable_type/:favoritable_id' do
    resources :favorites
  end
  scope "/:commentable_type/:commentable_id" do
    resources :comments, :as => :commentable_comments do 
      member do
        get :unsubscribe
      end      
    end
  end
  resources :comments
  delete '/comments/delete_selected' => 'comments#delete_selected', :as => :delete_selected_comments
  
  resources :homepage_features
  resources :metro_areas
  resources :ads

  resources :activities
  
  resources :users do
    
    get 'page/:page', :action => :index, :on => :collection
    
    collection do
      post 'return_admin'
      delete 'delete_selected'
    end
    member do
      get 'dashboard'
      get 'edit_account'
      get 'invite'
      get 'signup_completed'      
      get 'activate'
      
      put 'toggle_moderator'
      put 'toggle_featured'

      put 'change_profile_photo'
      put 'update_account'
      put 'deactivate'      
      
      get 'welcome_photo'
      get 'welcome_about'
      get 'welcome_invite'
      get 'welcome_complete'
      
      post 'assume'               
      
      get 'statistics'
      get 'crop_profile_photo'
      put 'crop_profile_photo'
      get 'upload_profile_photo'
      put 'upload_profile_photo'
    end
    
    resources :friendships do
      collection do
        get :accepted
        get :pending
        get :denied
      end
      member do
        put :accept
        put :deny
      end
    end

    resources :photos do
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :posts do
      get 'page/:page', :action => :index, :on => :collection            
      
      collection do 
        # get 'manage(/page/:page)', :action => :manage
        get :manage
      end
      
      member do
        post :send_to_friend
        put :update_views
        get :category_tips_update
        get :preview
      end
    end

    resources :clippings

    resources :activities do
      get 'page/:page', :action => :index, :on => :collection  
      collection do
        get :network
      end
    end

    resources :invitations

    resources :favorites
    resources :messages do
      post :auto_complete_for_username, :on => :collection
      collection do
        post :delete_message_threads
        post :delete_selected

      end
    end

    resources :comments
    resources :photo_manager

    resources :albums do
      resources :photos do
        collection do
          post :swfupload
          get :slideshow
        end
      end
    end

  end

  resources :votes
  resources :invitations
  get '/users/:user_id/posts/category/:category_name' => 'posts#index', :as => :users_posts_in_category
  post '/users/metro_area_update' => 'users#metro_area_update', :as => :users_metro_area_update

end

app/views/shared/_admin_nav.html.haml
-box do
  %h3=:admin.l

  %ul.list
    %li= link_to_unless_current :features.l, homepage_features_path
    %li= link_to_unless_current :categories.l, categories_path
    %li= link_to_unless_current :metro_areas.l, metro_areas_path
    %li= link_to_unless_current :events.l, admin_events_path
    %li= link_to_unless_current :statistics.l, statistics_path
    %li= link_to_unless_current :ads.l, ads_path 
    %li= link_to_unless_current :comments.l, admin_comments_path 
    %li= link_to_unless_current :tags.l, admin_tags_path
    %li= link_to_unless_current :admin_pages.l, admin_pages_path
    - if @admin_nav_links.any?
      - @admin_nav_links.each do |link|
        %li=link_to link[:name], link[:url]
    
    
    %li= link_to :cache_clear_link.l, admin_clear_cache_path, :confirm => :are_you_sure.l

app/views/shared/_bio_help.html.haml
- if @user.vendor?
  = :user_vendor_offer.l
- else
  = :user_bio_help.l

app/views/shared/_box.html.haml
.box{html_options}
  %div{:class => "#{html_options[:content_class]}"}
    =body

app/views/shared/_contact.html.haml
-box :class => "alt" do 
  %h3=:need_to_contact_us.l
  %p
    =:dont_wait_its.l
    %a{:href=>"mailto:#{configatron.support_email}"}= configatron.support_email

app/views/shared/_end_javascript.html.haml
= javascript_include_tag 'community_engine'
= tiny_mce_init_if_needed
- if forum_page?
  = javascript_include_tag 'forum'

-if show_footer_content?        
  :javascript
    #{remote_function(:update => "footer_content", :method => :get, :url =>  footer_content_url )}

app/views/shared/_explore.html.haml
-box do
  %h3 Explore
  %ul.list.checks
    - Category.find(:all).each do |c|
      %li= link_to c.name, category_path(c)
    %li= link_to :whats_popular.l, popular_url, {:class => 'popular'}
    - Page.find(:all).each do |page|
      - if (logged_in? || page.page_public)
        %li= link_to page.title, pages_path(page)

app/views/shared/_footer_content.html.haml
.yui-u.first
  -box :class => "fresh" do 
    %h3=:whats_fresh.l
    - @recent_activity.each do |activity|
      =render :partial => "activities/activity", :locals => {:activity => activity }
    %h6.all= link_to :see_all_activity.l, activities_path

.yui-u
  -box do 
    %h3=:tags.l
    - tag_cloud @popular_tags, %w(nube1 nube2 nube3 nube4 nube5) do |tag, css_class|
      = link_to tag.name, tag_path(tag.to_param), :class => css_class
    %h6.all=link_to :all_tags.l, tags_path

app/views/shared/_header.html.haml
#hd
  %h1
  #sub_wrapper
    .olca_header
    .headerlogo
      = image_tag 'olca_mission_logo.jpg', :plugin => 'community_engine'
    - if logged_in?
      = render :partial => 'shared/user_menu'
      - if current_user.unread_messages?
        %h2#newmail
          = link_to :unread_messages.l(:count => current_user.unread_message_count), user_messages_path(current_user)
    - else

  #NavBar
    %ul
      - Category.find(:all).each do |c|
        = topnav_tab c.name, {:url => category_path(c), :section => [c.name]}
      = topnav_tab :forums.l, { :url => forums_path, :section => ['forums'] }
      = topnav_tab :popular.l, { :url => popular_path, :section => ['popular'] }
      = topnav_tab :people.l, { :url => users_path, :section => ['users'] }
      - if current_user 
        = topnav_tab :my_profile.l, { :url => user_path(current_user), :section => ['my_profile']}   
      - if @header_tabs.any?
        - @header_tabs.each do |tab|
          = topnav_tab tab[:name], {:url => tab[:url], :section => [tab[:section]] } 
      
    / SiteSearch Google 
    %form{:method=>"get", :action=>"http://www.google.com/custom", :target=>"_top"}
      %input{ :type=>"hidden", :name=>"domains", :value=>"#{home_url}"}
      %label{ :for=>"search",  :style=>"display: none"}
        = :search.l+" #{configatron.community_name}"
      %input{ :type=>"text",:name=>"q", :size=>"17", :maxlength=>"255", :id=>"search"}
      %input{ :type=>"hidden", :name=>"sitesearch", :value=>"#{home_url}", :id=>"ss1"}
      %input{ :type=>"hidden", :name=>"client", :value=>"pub-9113954708528841"}
      %input{ :type=>"hidden", :name=>"forid", :value=>"1"}
      %input{ :type=>"hidden", :name=>"channel", :value=>"1842224655"}
      %input{ :type=>"hidden", :name=>"ie", :value=>"ISO-8859-1"}
      %input{ :type=>"hidden", :name=>"oe", :value=>"ISO-8859-1"}
      %input{ :type=>"hidden", :name=>"cof", :value=>"GALT:#008000;GL:1;DIV:#FFFFFF;VLC:663399;AH:center;BGC:FFFFFF;LBGC:FFFFFF;ALC:0066CC;LC:0066CC;T:000000;GFNT:0000FF;GIMP:0000FF;LH:50;LW:90;S:http://#{home_url};FORID:1"}
      %input{ :type=>"hidden", :name=>"hl", :value=>"en"}
      
  / NavBar 
/ header

app/views/shared/_location_chooser.html.haml
#location_chooser
  %label= :country.l
  = select_tag(:country_id, options_from_collection_for_select(Country.find_countries_with_metros, "id", "name", selected_country), {:include_blank => true})

  %br
  %label= :state.l 
  = select_tag(:state_id, options_from_collection_for_select(states, "id", "name", (selected_state rescue nil)), {:disabled => states.empty? })

  = image_tag 'spinner.gif', :style => 'display:none;'

  %br
  %label= :metro_area.l
  = select_tag(:metro_area_id, options_from_collection_for_select(metro_areas, "id", "name", (selected_metro_area rescue nil)), {:disabled => metro_areas.empty? })

  = image_tag 'spinner.gif', :style => 'display:none;'

%span

- js ||= nil
- if js
  = observe_field("state_id", {:url => {:controller => 'users', :action => 'metro_area_update'}, :with => "'state_id=' + $('state_id').value + '&country_id=' + $('country_id').value", :loading => "$$('div#location_chooser img')[0].show();", 500 => "alert('"+:sorry_there_was_an_error.l+"'); return false", :update => "location_chooser"})
  = observe_field("country_id", {:url => {:controller => 'users', :action => 'metro_area_update'}, :with => "country_id", :loading => "$$('div#location_chooser img')[0].show();", 500 => "alert('"+:sorry_there_was_an_error.l+"'); return false", :update => "location_chooser"})
- else
  -content_for :end_javascript do
    = observe_field("state_id", {:url => {:controller => 'users', :action => 'metro_area_update'}, :with => "'state_id=' + $('state_id').value + '&country_id=' + $('country_id').value", :loading => "$$('div#location_chooser img')[0].show();", 500 => "alert('"+:sorry_there_was_an_error.l+"'); return false", :update => "location_chooser"})
    = observe_field("country_id", {:url => {:controller => 'users', :action => 'metro_area_update'}, :with => "country_id", :loading => "$$('div#location_chooser img')[0].show();", 500 => "alert('"+:sorry_there_was_an_error.l+"'); return false", :update => "location_chooser"})
  

app/views/shared/_login_sidebar.html.haml
-box do
  %h3=:help.l
  %p
    =:dont_have_an_account.l
    %br/
    = link_to :click_here_to_sign_up.l, "/signup"
  %p
    =:forgot_your_password.l
    %br/
    = link_to :click_here_to_retrieve_it.l, forgot_password_url
  %p
    =:forgot_your_username.l
    %br/
    = link_to :click_here_to_retrieve_it.l, forgot_username_url

app/views/shared/_messages.html.haml
- %w(info notice error).each do |type|
  - if flash[type.to_sym]
    .warning.flash_message{:class => "#{type.to_s}"}
      %span= h(flash[type.to_sym])
      %small
        %a{:href=>"#", :onclick=>"$$('div.flash_message')[0].hide();return false"}=:close_this_message.l
      
      

app/views/shared/_scripts_and_styles.html.haml
= stylesheet_link_tag 'community_engine'

- if forum_page?
  = stylesheet_link_tag 'forum'
  - unless @feed_icons.blank?
    - @feed_icons.each do |feed|
      = auto_discovery_link_tag :rss, feed[:url], :title => "Subscribe to '#{feed[:title]}'"

= yield :head_css

app/views/shared/_user_menu.html.haml
%h2#user-menu
  =:logged_in.l
  = link_to current_user.login, dashboard_user_path(current_user)
  #user-menu-tip
    %ul
      -if current_user.admin?
        %li=link_to :admin_dashboard.l, admin_dashboard_path
      %li= link_to :edit_profile.l, edit_user_path(current_user)
      %li= link_to :edit_account.l, edit_account_user_path(current_user)
      %li= link_to :manage_posts.l, manage_user_posts_path(current_user)
      %li= link_to :inbox.l, user_messages_path(current_user)

    %hr
    %ul
      %li= link_to :my_profile.l, user_path(current_user)
      %li=link_to :my_blog.l, user_posts_path(current_user)
      %li=link_to :photo_manager.l, user_photo_manager_index_path(current_user)
      %li=link_to :my_clippings.l, user_clippings_path(current_user)
      %li=link_to :my_friends.l, accepted_user_friendships_path(current_user)
    %hr
    =link_to :log_out.l, logout_path